---
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.14.14
    hooks:
      # Run the linter.
      - id: ruff-check
        args: [--fix, --exit-non-zero-on-fix]
        types_or: [ python, pyi ]
        stages: [pre-commit]        
      # Run the formatter.
      - id: ruff-format
        args: [--exit-non-zero-on-format] # Needed for GH Action to fail
        types_or: [ python, pyi ]
        stages: [pre-commit]
  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: pytest -W error::RuntimeWarning tests/ --cov=src/scores --cov-report term-missing
        language: system
        stages: [pre-push]
        always_run: true
        pass_filenames: false
      - id: doctest
        name: doctest
        entry: pytest --doctest-modules src/scores/ --override-ini="addopts="
        language: system
        stages: [pre-commit, pre-push]
        always_run: true
        pass_filenames: false
      - id: ty-check
        name: ty-check
        entry: ty check
        language: system
        pass_filenames: false
        types: [python]