# NOTE: Although scores is available on conda, this uses pip in order
# to install the `all` variant, as conda only has the `minimal` variant.
# This file is for use by contributors who likely want the `all` variant
# dependencies in an environment.
name: scores
channels:
  - defaults
dependencies:
  - pip
  - pip:
    - scores[all]
